#!/bin/bash

# set up the two monitors for bspwm
# NOTE This is a simplistic approach because I already know the settings I
# want to apply.
my_laptop_external_monitor=$(xrandr --query | grep 'VGA-1')
if [[ $my_laptop_external_monitor = *connected* ]]; then
    xrandr --output LVDS-1 --primary --mode 1280x800 --rotate normal --output VGA-1 --mode 1920x1080 --rotate normal --right-of LVDS-1
fi
